spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/main
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jdbc:
    template:
      fetch-size: 50

flyway:
  enabled: true
  locations: classpath:db/migration